apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-ingress
  namespace: reddit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    -  app.redabokka.online
    secretName: reddit-tls
  rules:
  - host: app.redabokka.online
    http:
      paths:
      - path: /app
        pathType: Exact
        backend:
          service:
            name: reddit-service
            port:
              number: 3000
